name: Update Fonts List

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  get-fonts-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Fetch Fonts List
        env:
          GOOGLE_FONTS_API_KEY: ${{ secrets.GOOGLE_FONTS_API_KEY }}
        run: |
          curl -o ./src/assets/font-list.json \
            "https://www.googleapis.com/webfonts/v1/webfonts?key=${GOOGLE_FONTS_API_KEY}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: font-list-${{ env.TODAY }}
          delete-branch: true
          title: Update fonts list
