name: Documentation

on:
  release:
    types:
      - created

jobs:
  job:
    name: Documentation
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: PACKAGENAME
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip3 install poetry
          poetry install
      - name: Build docs
        run: |
          poetry run sphinx-apidoc -efTM -t docs/_templates/apidoc -o docs/_source ${{ env.PACKAGE_NAME }}
          poetry run sphinx-build -a docs docs/_build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
